### ISSUE TITLE
Investigation into automating our propType tables

### ISSUE THREAD

**Issue by omgaz** [Adslot/adslot-ui#732]
### Auto Prop Types Proposal

Using `react-docgen` to output a generated proptypes json file we should be able to create the following.

#### Alert Component Example

__Step 1:__

Move `docs/examples/AlertExample.jsx` to `docs/examples/Alert/index.jsx`

__Step 2:__

Generate propTypes from component using CLI (automate this for each component)

```bash
node ./node_modules/react-docgen/bin/react-docgen.js 
./src/components/alexandria/Alert/index.jsx -o ./docs/examples/Alert/generatedPropTypes.json --pretty
```
Output:

```json
{
  "description": "",
  "displayName": "AlexandriaAlertComponent",
  "methods": [],
  "props": {
    "type": {
      "type": {
        "name": "enum",
        "value": [
          {
            "value": "'success'",
            "computed": false
          },
          {
            "value": "'info'",
            "computed": false
          },
          {
            "value": "'warning'",
            "computed": false
          },
          {
            "value": "'danger'",
            "computed": false
          }
        ]
      },
      "required": false,
      "description": "",
      "defaultValue": {
        "value": "'info'",
        "computed": false
      }
    },
    "children": {
      "type": {
        "name": "node"
      },
      "required": true,
      "description": ""
    },
    "dts": {
      "type": {
        "name": "string"
      },
      "required": false,
      "description": ""
    }
  }
}
```

__Step 3__

Update Example and PropTypeTable components to read this new format (also adding required column to end)

`docs/examples/Alert/index.jsx`

```js
...
import generatedPropTypes from './generatedPropTypes.json';

...

const exampleProps = {
  componentName: generatedPropTypes.displayName,
  ...
  props: generatedPropTypes.props,
}
...
```

`docs/components/PropTypeTable/index.jsx`

```jsx
<tbody>
  {_.map(props, ({ type, defaultValue, description, required }, name) => {
    const enumString = type.name === 'enum' ? ` of: ${_.map(type.value, 'value').join(', ')}` : '';
    return <tr key={name}>
      <td><code>{name}</code></td>
      <td><code>{type.name}{enumString}</code></td>
      <td><code>{defaultValue ? defaultValue.value : null}</code></td>
      <td><i>{description}</i></td>
      <td className="text-center">{required ? <input type="checkbox" read-only checked /> : null}</td>
    </tr>
  })}
</tbody>
```

![proptypes table](https://user-images.githubusercontent.com/908155/42612154-0acb1298-85dd-11e8-9962-2a9d96fb351e.PNG)

**Step 4**

Manually move all `notes` to comments above each propType

**Step 5**

Make sure we re-generate propTypes either on change of component or on pre-commit.

WIP Invetigation https://github.com/Adslot/adslot-ui/pull/733

## Tasks to consider

- [ ] merge adslot ui and alexandria componnents
- [ ] give every component a better display name
- [ ] move notes from example to comments in code
- [ ] check third-party components

**Comment by ChaoLiangSuper** [comment]
Three concerns:
1. This proptype table is based on each component. So what will do if one component has several proptype tables? For example, some nested component(Grid, GridRow, and GridCell), we use three proptype tables.

2. For example, prop `dts`. Do we need to write a description of `dts` in every component?

3. The current behaviour is if we don't want to show propType table, it just renders a header. How about the new one?

I do agree with:
Merge adslot ui and alexandria together and giving better display names.

Also, we can implement `pagination`on the doc, for example, each page has its own component instead `scrolling`.

**Comment by omgaz** [comment]
> 1. This proptype table is based on each component. So what will do if one component has several proptype tables? For example, some nested component(Grid, GridRow, and GridCell), we use three proptype tables.

This is tricky and right now I can't think of a clean solution. There are webpack modules for react-docgen that might automate something like this.

The solution I see now would be to treat these edge cases as manual. Manually generate the files for these subComponents, manually import them and have the `Example` component support `props` and `subComponentProps` -> much like the propTypeSections. This would require manual effort for these edge cases.

`react-docgen` can accept multiple input files and render one output -> maybe this can be considered too.

---

> 2. For example, prop dts. Do we need to write a description of dts in every component?

I think we'll be able to detect something like this in the table component

Either on the description:
```jsx
<td>{type.name === 'dts' ? 'this is the data test selector help text' : description}</td>
```

or on the name, being a link to a note somewhere on DTS (preferred)
```jsx
<td>{type.name === 'dts' ? <a href="#dts">dts</a> : type.name}</td>
```

---

> 3. The current behaviour is if we don't want to show propType table, it just renders a header. How about the new one?

I guess this will be a case-by-case basis. If we don't have generated prop types we can choose to render nothing.

```jsx
_.isEmpty(generatedPropTypes.props) ? null : <PropTypesTable props={generatedPropTypes.props} />
```

Alternatively we can choose to not generate or import them.

**Comment by omgaz** [comment]
Third party bootstrap components don't seem to like being generated:

```
Error: No suitable component definition found.
```

The bootstrap components are .js and not .jsx and relyinng on prototyping methods and prop types onto the function creators. For these components we'll either have to add the bootstrap props to a manual table or simply refer to their documentation through a link.

**Comment by veegandhi** [comment]
Closed as part of #960
