### ISSUE TITLE
[CheckList] v27 

### ISSUE THREAD

**Issue by ChaoLiangSuper** [Adslot/adslot-ui#791]
Version 27 Checklist

- [ ] Partial selected checkbox component
- [ ] Introduce `theme` to popover/tooltip (Dark/Light)
- [ ] Update `react-select` to v2
- [ ] Introduce `popper.js` to popover/tooltip for flipping behaviour

**Comment by lightbringer1991** [comment]
can put this into a project

**Comment by ChaoLiangSuper** [comment]
Sure Closing this
