### ISSUE TITLE
Creates a v27 feature branch

### ISSUE THREAD

**Issue by lightbringer1991** [Adslot/adslot-ui#801]
Creates a v27 feature branch, so we don't mix bug fixes with the feature release intended for v27

## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Something else (idea, build tool, documentation improvement)

## Expected Behaviour and Accepted Behaviour

- [ ] Should …
- [ ] Should …
- [ ] Should …

## Steps to Reproduce (for bugs)

1.
1.
1.
1.

**Comment by ChaoLiangSuper** [comment]
Don't think we need it. Closing this issue. Explanation can be seen in the above PR.
