### ISSUE TITLE
Documentation Roadmap

### ISSUE THREAD

**Issue by veegandhi** [Adslot/adslot-ui#915]
Placeholder for Documentation update ideas and planning

## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Something else (idea, build tool, documentation improvement)

## Description

Minimum requirement: 
- Working examples / sandbox demos
- Once code per page
- Prop cleanup 
- Getting started/installation

**Comment by bchew** [comment]
Completed
